### ISSUE TITLE
No module named commandlineapp

### ISSUE THREAD

**Issue by joereynolds** [JNRowe/shell-doctest#1]
After trying both `python setup.py build` and `python setup.py install` I get an error about commandlineapp not existing.

Is there something I could be missing trying to run this?

**Comment by JNRowe** [comment]
[Sorry for the delay, I've been on vacation.]

As the description says this is just a mirror, and therefore not an active project.

> After trying both `python setup.py build` and `python setup.py install` I get an error about commandlineapp not existing
> 
> Is there something I could be missing trying to run this?

`shell-doctest` comes from the dark ages, and doesn't handle its dependencies in the modern way.  You can either exchange the `distutils` setup for `setuptools` in `setup.py`, or manually install the dependencies listed in `setup.py`.

Honestly, I'd recommend using something else anyway.  A quick poll in the office says `cram` is popular for similar tasks, and I'm only using `shell-doctest` on a remaining few legacy projects myself.
